version: 2.1

orbs:
  gh: circleci/github-cli@2.2.0
  sdkman: joshdholtz/sdkman@0.2.0

jobs:
  arm64-native:
    machine:
      image: ubuntu-2004:current
      resource_class: arm.medium
    steps:
      - checkout
      - sdkman/setup-sdkman
      - sdkman/sdkman-install:
          candidate: java
          version: 22.3.1.r17-grl
      - run:
          name: "native compile"
          command: "./mvnw -Pnative clean native:compile"
      - gh/setup
      - run:
          name: "upload release asset"
          command: gh release upload "${CIRCLE_TAG}" ./target/initializr-plusplus-linux-aarch_64
          
workflows:
  arm64-native-workflow:
    jobs:
      - arm64-native:
          context:
            - dashaun-github
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/