version: 2.1

orbs:
  gh: circleci/github-cli@2.2.0
  sdkman: joshdholtz/sdkman@0.2.0

jobs:
  create-gh-release:
    machine:
      image: ubuntu-2004:current
      resource_class: medium
    steps:
      - checkout
      - gh/setup
      - run:
          name: "upload release asset"
          command: gh release create "${CIRCLE_TAG}" -t "${CIRCLE_TAG}" -n "${CIRCLE_TAG}"
  arm64-native:
    machine:
      image: ubuntu-2004:current
      resource_class: arm.medium
    steps:
      - checkout
      - sdkman/setup-sdkman
      - sdkman/sdkman-install:
          candidate: java
          version: 22.3.1.r17-grl
      - run:
          name: "native compile"
          command: "./mvnw -Pnative clean native:compile"
      - gh/setup
      - run:
          name: "upload release asset"
          command: gh release upload "${CIRCLE_TAG}" ./target/initializr-plusplus-linux-aarch_64
  macos-arm64-native:
    docker:
      - image: cimg/base:current
    resource_class: dashaun/juice-v2
    steps:
      - checkout
      - sdkman/setup-sdkman
      - sdkman/sdkman-install:
          candidate: java
          version: 22.3.1.r17-grl
      - run:
          name: "native compile"
          command: "sdk env && ./mvnw -Pnative clean native:compile -DskipTests"
      - run:
          name: "upload release asset"
          command: gh release upload "${CIRCLE_TAG}" ./target/initializr-plusplus-osx-aarch_64
workflows:
  create-gh-release:
    jobs:
      - create-gh-release:
          context:
            - dashaun-github
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  arm64-native-workflow:
    jobs:
      - arm64-native:
          context:
            - dashaun-github
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  macos-arm64-workflow:
    jobs:
      - macos-arm64-native:
          context:
            - dashaun-github
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/               