---
name: "tagged-linux"

on:
  push:
    tags:
      - "v*"

jobs:
    
  tagged-linux:
    name: "Tagged linux"
    runs-on: ubuntu-latest

    steps:
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: "${{ secrets.GH_TOKEN }}"

      - uses: actions/checkout@v3
        with:
          ref: '${{github.ref_name}}'

      - name: Build Image
        run: ./mvnw -Pnative native:compile -DskipTests
        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            ./target/initializr-plusplus-linux-x86_64